language: python
python:
  - 2.7.14
  - 3.5.2
  - 3.6.4
script:
  - JARDIN_CONF=/home/travis/build/instacart/jardin/tests/jardin_conf_pg.py python setup.py test
  - JARDIN_CONF=/home/travis/build/instacart/jardin/tests/jardin_conf_mysql.py python setup.py test
  - JARDIN_CONF=/home/travis/build/instacart/jardin/tests/jardin_conf_sqlite.py python setup.py test
services:
  - postgresql
  - mysql
before_script:
  - psql --version
  - psql -c 'create database jardin_test;' -U postgres
  - mysql -e 'CREATE DATABASE jardin_test;'
addons:
  postgresql: 10
